### ISSUE TITLE
[feature request] add option to automatically go into a specific mode

### ISSUE THREAD

**Issue by badbob001** [dralletje/Windowed#21]
Add an extension setting to automatically go into a specific mode (eg: windowed) when a supported video page is loaded. So for me, I always want the youtube video page to load in windowed mode.

**Comment by dralletje** [comment]
This is in the newest Firefox release! Coming to a Chrome webstore near you soon!

**Comment by badbob001** [comment]
I'm waiting for chrome support for the new feature but I did check it out on firefox. What I'm seeing is that while I can specify the default mode, I still need to click the fullscreen icon to go to that default mode. What I was was looking for was to remove the need to click anything. That is, if I go to the page for the video, it will automatically go to the default mode.

**Comment by dralletje** [comment]
Ahhh, alright

I can't automatically go into a mode, because I don't know what part of the website needs to be fullscreen. The extension could remember what part was previously fullscreen, but that isn't reliable. I could also make it site-specific, so only support this on YouTube, but that feels wrong.

You could use another extension that automatically puts your specific site in full screen (or can automatically click a button) and combine that with Windowed's default mode setting.
